# Generated by Django 3.0.8 on 2020-08-05 00:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0009_auto_20200804_2000'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categories',
            name='category',
            field=models.CharField(default=None, max_length=11),
        ),
    ]
