# Generated by Django 3.0.8 on 2020-08-05 00:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0010_auto_20200804_2028'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categories',
            name='category',
            field=models.CharField(choices=[(None, 'Uncategorized'), ('Art', 'Art'), ('Books', 'Books'), ('Electronics', 'Electronics'), ('Toys', 'Toys'), ('Hobby', 'Hobby'), ('Home', 'Home'), ('Sports', 'Sports'), ('Vehicles', 'Vehicles')], default=None, max_length=11),
        ),
    ]
